### ISSUE TITLE
Make the GUI using Tkinter.

### ISSUE THREAD

**Issue by roshniRam** [NJACKWinterOfCode/Printed-Text-recognition-and-conversion#19]
Make the GUI similar to the one made using PyQt4. It should be able to import an image for text recognition.
Screenshot of the GUI made using PyQt4 -
![ocr2](https://user-images.githubusercontent.com/30633549/49701655-d2bdce00-fc14-11e8-9a82-1c864daad62d.png)

**Comment by adityaRakhecha** [comment]
I would like to work on this. Please assign this issue to me.

**Comment by roshniRam** [comment]
Sure
